name: "encoder"
backend: "onnxruntime"
default_model_filename: "model.onnx"

max_batch_size: 128


sequence_batching{
  max_sequence_idle_microseconds: 15000000
  oldest {
    max_candidate_sequences: 1024
    preferred_batch_size: [32, 64, 128]
    max_queue_delay_microseconds: 300
  }
  control_input [
  ]
  state [
  ]
}


input [
  {
    name: "speech"
    data_type: TYPE_FP32
    dims: [-1, 560]
  },
  {
    name: "speech_lengths"
    data_type: TYPE_INT32
    dims: [1]
    reshape: { shape: [] }
  }
]

output [
  {
    name: "enc"
    data_type: TYPE_FP32
    dims: [-1, 512]
  },
  {
    name: "enc_len"
    data_type: TYPE_INT32
    dims: [1]
    reshape: { shape: [ ] }
  },
  {
    name: "alphas"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

parameters { key: "cudnn_conv_algo_search" value: { string_value: "2" } }

instance_group [
  {
    count: 2
    kind: KIND_GPU
  }
]