name: "feature_extractor"
backend: "python"
max_batch_size: 128

parameters [
  {
    key: "chunk_size_s",
    value: { string_value: "0.6"}
  },
  {
    key: "config_path"
    value: { string_value: "model/feature_extractor/config.yaml"}
  }
]

sequence_batching{
    max_sequence_idle_microseconds: 15000000
    oldest {
      max_candidate_sequences: 1024
      preferred_batch_size: [32, 64, 128]
      max_queue_delay_microseconds: 300
    }
    control_input [
        {
            name: "START",
            control [
                {
                    kind: CONTROL_SEQUENCE_START
                    fp32_false_true: [0, 1]
                }
            ]
        },
        {
            name: "READY"
            control [
                {
                    kind: CONTROL_SEQUENCE_READY
                    fp32_false_true: [0, 1]
                }
            ]
        },
        {
            name: "CORRID",
            control [
                {
                    kind: CONTROL_SEQUENCE_CORRID
                    data_type: TYPE_UINT64
                }
            ]
        },
        {
            name: "END",
            control [
                {
                    kind: CONTROL_SEQUENCE_END
                    fp32_false_true: [0, 1]
                }
            ]
        }
    ]
}


input [
  {
    name: "wav"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

output [
  {
    name: "speech"
    data_type: TYPE_FP32
    dims: [61, 80]  # 80
  }
]


instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]

